# shellcheck disable=SC2091
$(javac Acceptor.java)
$(javac Learner.java)
$(javac Proposal.java)
$(javac Proposer.java)
$(javac ProposerInterface.java)
$(javac Server.java)
$(javac ServerDriver.java)
$(javac ServerInterface.java)
$(javac ServerLogger.java)
$(javac DatabaseServer.java)
$(javac DatabaseServerInterface.java)
$(javac Task.java)
$(javac TaskType.java)
$(javac Client.java)
$(javac ClientLogger.java)
$(javac ClientRequest.java)
$(javac ClientInterface.java)
